language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.3)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

before_install:
  - source .travis/setenv_lua.sh
  - pip install --user cpp-coveralls
  - luarocks install Lua-cURL         --server=https://luarocks.org/dev
  - luarocks install luacov-coveralls --server=https://luarocks.org/dev
  - luarocks install telescope 0.6.0 --server=http://rocks.moonscript.org

script: "tsc -f specs/*"
  
after_success:
  - luacov-coveralls -c .luacov -e 30log-

notifications:
  email:
    on_success: change
    on_failure: always
